frr defaults traditional
hostname r3
!
interface r3-eth0
 ip address 192.168.13.2/30
!
interface r3-eth1
 ip address 192.168.23.2/30
!
mpls lsp 100 192.168.23.1 implicit-null
mpls lsp 200 192.168.13.1 implicit-null
